# Generated by Django 4.2.6 on 2024-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='form_name',
            field=models.CharField(max_length=100),
        ),
    ]
