# Generated by Django 4.2.6 on 2024-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mediapost_image1_alter_mediapost_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('required_skills', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
