# Generated by Django 4.2.6 on 2024-04-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
