# Generated by Django 4.2.6 on 2024-04-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_job_company_logo_remove_job_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
