# Generated by Django 4.2.6 on 2024-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='image1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='image2',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
