# Generated by Django 4.2.6 on 2024-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userregistration_terms_of_use_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='country_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='terms_of_use_agreed',
            field=models.BooleanField(),
        ),
    ]
