# Generated by Django 4.2.6 on 2024-04-10 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userregistration_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
