# Generated by Django 4.2.6 on 2024-04-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_userregistration_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='hear_about_opportunities',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='receive_job_notifications',
        ),
    ]
