# Generated by Django 4.2.6 on 2024-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_jobapplication_delete_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('aadhar_card_number', models.CharField(max_length=200)),
                ('is_fresher', models.CharField(max_length=200)),
                ('applied_with_tsar_it', models.CharField(max_length=200)),
                ('previous_employee_id', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('terms_of_use_agreed', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
