# Generated by Django 4.2.6 on 2024-04-16 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_jobapply_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='form_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
