# Generated by Django 4.2.6 on 2024-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_jobapply_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
