# Generated by Django 4.2.6 on 2024-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_jobapply_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='aadhar_card_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='applied_with_tsar_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='country_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='is_fresher',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='previous_employee_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='terms_of_use_agreed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
