# Generated by Django 4.2.6 on 2024-06-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_job_date_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='form_name',
            field=models.CharField(max_length=100),
        ),
    ]
