# Generated by Django 4.2.6 on 2024-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_jobapply_applied_with_tsar_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='application_date',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='applied_jobs',
            field=models.ManyToManyField(related_name='applicants', to='app.job'),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='aadhar_card_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='applied_with_tsar_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='form_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='is_fresher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='terms_of_use_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
